name: CD Apply Workflow

on:
  workflow_call:
    inputs:
      tf_action:
        required: true
        type: string
      config_path:
        required: true
        type: string

jobs:
  extract-env:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.setenv.outputs.env }}
    steps:
      - id: setenv
        run: |
          IFS='/' read -r client cloud env <<< "${{ inputs.config_path }}"
          echo "env=$env"
          echo "env=$env" >> $GITHUB_OUTPUT

  terraform-apply:
    needs: extract-env
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.extract-env.outputs.environment }}
      url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - name: Checkout cc-client-config-repo
        uses: actions/checkout@v3

      - name: Checkout IAC repo
        uses: actions/checkout@v3
        with:
          repository: sasidaren-coder/github-actions-test
          path: iac

      - name: Export Terraform Secrets for Environment
        env:
          TF_VAR_confluent_cloud_api_key: ${{ vars.TF_CONFLUENT_CLOUD_API_KEY }}
          TF_VAR_confluent_cloud_api_secret: ${{ secrets.TF_CONFLUENT_CLOUD_API_SECRET }}
          TF_VAR_kafka_cluster_id: ${{ vars.TF_KAFKA_CLUSTER_ID }}
          TF_VAR_cc_environment_id: ${{ vars.TF_CC_ENVIRONMENT_ID }}
          TF_VAR_kafka_rest_endpoint: ${{ vars.TF_KAFKA_REST_ENDPOINT }}
          TF_VAR_kafka_api_key: ${{ vars.TF_KAFKA_API_KEY }}
          TF_VAR_kafka_api_secret: ${{ secrets.TF_KAFKA_API_SECRET }}
          TF_VAR_resource_yaml_path: ../../${{ inputs.config_path }}/resources.yaml
        run: |
          echo "Exporting TF_VAR_* variables..."
          echo "TF_VAR_confluent_cloud_api_key=$TF_VAR_confluent_cloud_api_key" >> $GITHUB_ENV
          echo "TF_VAR_confluent_cloud_api_secret=$TF_VAR_confluent_cloud_api_secret" >> $GITHUB_ENV
          echo "TF_VAR_kafka_cluster_id=$TF_VAR_kafka_cluster_id" >> $GITHUB_ENV
          echo "TF_VAR_cc_environment_id=$TF_VAR_cc_environment_id" >> $GITHUB_ENV
          echo "TF_VAR_kafka_rest_endpoint=$TF_VAR_kafka_rest_endpoint" >> $GITHUB_ENV
          echo "TF_VAR_kafka_api_key=$TF_VAR_kafka_api_key" >> $GITHUB_ENV
          echo "TF_VAR_kafka_api_secret=$TF_VAR_kafka_api_secret" >> $GITHUB_ENV
          echo "TF_VAR_resource_yaml_path=$TF_VAR_resource_yaml_path" >> $GITHUB_ENV

      - name: Install Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform Init
        working-directory: iac/confluentcloud-resource-provisioner-tf
        run: terraform init

      - name: Terraform Validate
        working-directory: iac/confluentcloud-resource-provisioner-tf
        run: terraform validate

      - name: Terraform Plan
        working-directory: iac/confluentcloud-resource-provisioner-tf
        run: |
          echo "Working Directory: $(pwd)"
          echo "Listing Files: $(ls -ltr ../..)"
          terraform plan -var-file=env/dev.terraform.tfvars -var="resource_yaml_path=../../${{ inputs.config_path }}/resources.yaml"

      - name: Terraform Apply
        working-directory: iac/confluentcloud-resource-provisioner-tf
        run: |
          terraform apply -auto-approve \
            -var-file=env/dev.terraform.tfvars \
            -var="resource_yaml_path=../../${{ inputs.config_path }}/resources.yaml"