# on:
#   workflow_call:
#     inputs:
#       tf_action:
#         required: true
#         type: string  # "plan", "apply"
#       config_path:
#         required: true
#         type: string

# jobs:
#   job1-plan:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout github-actions-repo
#         uses: actions/checkout@v3
#         with:
#           repository: sasidaren-coder/github-actions-test
#           path: github-actions-test
#       - name: Checkout cc-client-config-repo
#         uses: actions/checkout@v3
#         with:
#           repository: sasidaren-coder/cc-client-config-repo
#           path: cc-client-config-repo
#       - name: Debug Working Directory
#         run: pwd && ls -al
#       - name: Custom rules
#         run: |
#           echo "Working Directory: $(pwd)"
#           chmod +x ./github-actions-test/scripts/validate-inputs.sh
#           ./github-actions-test/scripts/validate-inputs.sh ./cc-client-config-repo/${{ inputs.config_path }}
      
#       - name: Install Terraform CLI
#         uses: hashicorp/setup-terraform@v3
#         with:
#           terraform_version: 1.9.8 # Change to your preferred version

#       - name: Terraform Init
#         run: terraform init -backend-config=...
#       - name: Terraform Validate
#         run: terraform validate
#       - name: Terraform Plan
#         run: terraform plan -var-file=cc-client-config-repo/${{ inputs.config_path }}/terraform.tfvars


name: CI Plan Workflow

on:
  workflow_call:
    inputs:
      tf_action:
        required: true
        type: string  # "plan", "apply"
      config_path:
        required: true
        type: string

jobs:
  extract-env:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.setenv.outputs.env }}
      cloud_provider: ${{ steps.setenv.outputs.cloud_provider }}
    steps:
      - id: setenv
        run: |
          IFS='/' read -r client cloud env <<< "${{ inputs.config_path }}"
          echo "env=$env"
          echo "cloud_provider=$cloud"
          echo "env=$env" >> $GITHUB_OUTPUT
          echo "cloud_provider=$cloud" >> $GITHUB_ENV
  terraform-plan:
    needs: extract-env
    runs-on: ubuntu-latest
    environment:
      # name: ${{ needs.extract-env.outputs.environment }}
      name: ${{ needs.extract-env.outputs.environment }}
    steps:
      # This checks out the CALLER repo (cc-client-config-repo), which happens by default
      - name: Checkout cc-client-config-repo
        uses: actions/checkout@v3

      # This checks out the reusable IAC repo containing Terraform code and scripts
      - name: Checkout github-actions-test (iac-repo)
        uses: actions/checkout@v3
        with:
          repository: sasidaren-coder/github-actions-test
          path: iac

      # Run validation script from the iac repo
      - name: Validate inputs
        run: bash iac/scripts/validate-inputs.sh ${{ inputs.config_path }}/resources.yaml

      - name: Export Terraform Secrets for Environment
        run: |
          echo "TF_VAR_resource_yaml_path=../../${{ inputs.config_path }}/resources.yaml" >> $GITHUB_ENV
          echo "TF_VAR_cloud_provider=azure" >> $GITHUB_ENV
          echo "TF_VAR_azure_confluent_cloud_api_key=${{ vars.AZURE_CONFLUENT_API_KEY }}" >> $GITHUB_ENV
          echo "TF_VAR_azure_confluent_cloud_api_secret=${{ secrets.AZURE_CONFLUENT_API_SECRET }}" >> $GITHUB_ENV
          echo "TF_VAR_azure_kafka_cluster_id=${{ vars.AZURE_KAFKA_CLUSTER_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_azure_cc_environment_id=${{ vars.AZURE_CC_ENVIRONMENT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_azure_kafka_rest_endpoint=${{ vars.AZURE_KAFKA_REST_ENDPOINT }}" >> $GITHUB_ENV
          echo "TF_VAR_azure_kafka_api_key=${{ vars.AZURE_KAFKA_API_KEY }}" >> $GITHUB_ENV
          echo "TF_VAR_azure_kafka_api_secret=${{ secrets.AZURE_KAFKA_API_SECRET }}" >> $GITHUB_ENV
          echo "TF_VAR_gcp_confluent_cloud_api_key=${{ vars.GCP_CONFLUENT_API_KEY }}" >> $GITHUB_ENV
          echo "TF_VAR_gcp_confluent_cloud_api_secret=${{ secrets.GCP_CONFLUENT_API_SECRET }}" >> $GITHUB_ENV
          echo "TF_VAR_gcp_kafka_cluster_id=${{ vars.GCP_KAFKA_CLUSTER_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_gcp_cc_environment_id=${{ vars.GCP_CC_ENVIRONMENT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_gcp_kafka_rest_endpoint=${{ vars.GCP_KAFKA_REST_ENDPOINT }}" >> $GITHUB_ENV
          echo "TF_VAR_gcp_kafka_api_key=${{ vars.GCP_KAFKA_API_KEY }}" >> $GITHUB_ENV
          echo "TF_VAR_gcp_kafka_api_secret=${{ secrets.GCP_KAFKA_API_SECRET }}" >> $GITHUB_ENV
          echo "TF_VAR_aws_confluent_cloud_api_key=${{ vars.AWS_CONFLUENT_API_KEY }}" >> $GITHUB_ENV
          echo "TF_VAR_aws_confluent_cloud_api_secret=${{ secrets.AWS_CONFLUENT_API_SECRET }}" >> $GITHUB_ENV
          echo "TF_VAR_aws_kafka_cluster_id=${{ vars.AWS_KAFKA_CLUSTER_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_aws_cc_environment_id=${{ vars.AWS_CC_ENVIRONMENT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_aws_kafka_rest_endpoint=${{ vars.AWS_KAFKA_REST_ENDPOINT }}" >> $GITHUB_ENV
          echo "TF_VAR_aws_kafka_api_key=${{ vars.AWS_KAFKA_API_KEY }}" >> $GITHUB_ENV
          echo "TF_VAR_aws_kafka_api_secret=${{ secrets.AWS_KAFKA_API_SECRET }}" >> $GITHUB_ENV
          
      - name: Print env vars
        run: env | grep ^TF_VAR_

      - name: Install Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8 # Change to your preferred version

      # Terraform Init, Validate, Plan from the module in iac repo
      - name: Terraform Init
        working-directory: iac/confluentcloud-resource-provisioner-tf
        run: terraform init

      - name: Terraform Validate
        working-directory: iac/confluentcloud-resource-provisioner-tf
        run: terraform validate

      - name: Terraform Plan
        working-directory: iac/confluentcloud-resource-provisioner-tf
        run: |
          echo "Working Directory: $(pwd)"
          echo "Listing Files: $(ls -ltr ../..)"
          terraform plan
